version: '3.8'

services:
  # قاعدة البيانات
  mongodb:
    image: mongo:latest
    container_name: doctor-booking-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db

  # الخادم
  server:
    build: .
    container_name: doctor-booking-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/doctor-booking?authSource=admin
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - ./client:/app/client

volumes:
  mongodb_data:

