name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          close-issue-message: |
            This issue has been automatically closed due to inactivity. If you think
            this is still an issue, please open a new issue with more details.
          close-pr-message: |
            This pull request has been automatically closed due to inactivity. If you think
            this is still needed, please open a new pull request with more details.
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: pinned,security,bug,enhancement,good first issue,help wanted
          exempt-pr-labels: pinned,security,bug,enhancement,good first issue,help wanted
          exempt-issue-assignees: true
          exempt-pr-assignees: true
          exempt-issue-milestones: true
          exempt-pr-milestones: true
          exempt-issue-projects: true
          exempt-pr-projects: true
          only-issue-labels: ''
          only-pr-labels: ''
          operations-per-run: 100
          remove-stale-when-updated: true
          remove-stale-when-updated-ignore-updates: true
          debug-only: false
          ascending: false
          delete-branch: false
          start-date: ''
          ignore-issue-updates: true
          ignore-pr-updates: true
